# Generated by Django 4.1.4 on 2023-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
