# Generated by Django 4.1.4 on 2023-01-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.CharField(max_length=100)),
                ('player_2', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('winner', models.CharField(choices=[('Player 1', 'Player 1'), ('Player 2', 'Player 2')], max_length=8)),
            ],
        ),
    ]
